### ISSUE TITLE
HBuilderX编译到App出错

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-ui#24]
错误提示：

```
[HBuilder] 18:04:55.603 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[HBuilder] 18:04:55.603 ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[HBuilder] 18:04:55.636 Error: Missing binding /Users/bruce/Documents/work/my/tn/test/my-project/node_modules/node-sass/vendor/darwin-x64-57/binding.node
[HBuilder] 18:04:55.636 Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
[HBuilder] 18:04:55.669 Found bindings for the following environments:
[HBuilder] 18:04:55.670   - OS X 64-bit with Node.js 12.x
[HBuilder] 18:04:55.702 This usually happens because your environment has changed since running `npm install`.
[HBuilder] 18:04:55.733 Run `npm rebuild node-sass` to download the binding for your current environment.
[HBuilder] 18:04:55.763     at module.exports (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/node-sass/lib/binding.js:15:13)
[HBuilder] 18:04:55.793     at Object.<anonymous> (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/node-sass/lib/index.js:14:35)
[HBuilder] 18:04:55.794     at Module._compile (module.js:652:30)
[HBuilder] 18:04:55.824     at Object.Module._extensions..js (module.js:663:10)
[HBuilder] 18:04:55.825     at Module.load (module.js:565:32)
[HBuilder] 18:04:55.855     at tryModuleLoad (module.js:505:12)
[HBuilder] 18:04:55.855     at Function.Module._load (module.js:497:3)
[HBuilder] 18:04:55.886     at Module.require (module.js:596:17)
[HBuilder] 18:04:55.887     at require (internal/module.js:11:18)
[HBuilder] 18:04:55.916     at Object.sassLoader (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/sass-loader/lib/loader.js:46:72)
[HBuilder] 18:04:55.917     at runLoaders (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/webpack/lib/NormalModule.js:301:20)
[HBuilder] 18:04:55.947     at /Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[HBuilder] 18:04:55.948     at /Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[HBuilder] 18:04:55.977     at runSyncOrAsync (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
[HBuilder] 18:04:55.977     at iterateNormalLoaders (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[HBuilder] 18:04:56.008     at iterateNormalLoaders (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[HBuilder] 18:04:56.009     at /Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[HBuilder] 18:04:56.038     at Object.context.callback (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[HBuilder] 18:04:56.039     at Object.module.exports (/Users/bruce/Documents/work/my/tn/test/my-project/node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js:60:10)
[HBuilder] 18:04:56.070  ERROR  Build failed with errors.
[HBuilder] 18:04:56.070 项目 'my-project'导出失败
```

**Comment by brucehelen** [comment]
提示的命令 `npm rebuild node-sass` 执行都没问题。

**Comment by brucehelen** [comment]
`cli`方式创建的工程用的本机的node，HBuilderX用的自带node（版本号v8.x），两者版本不一致。导致这里的库有问题。项目建议直接使用HBuilderX，不要用cli方式创建。

**Comment by AndySkaura** [comment]
hbuilder打包app出现类似的报错。
vite项目，关闭  plugin-legacy后解决了
