### ISSUE TITLE
vue项目可以用uni-ui？

### ISSUE THREAD

**Issue by yinwhm12** [dcloudio/uni-ui#378]
你好！其他的vue项目，可以用uni-ui库？

**Comment by clai-wh** [comment]
可以

**Comment by yinwhm12** [comment]
引入后报了这种奇怪的错误，太奇怪了呀！安装官网的npm安装

34% building modules 201/228 modules 27 active ...ndexed-list\uni-indexed-list-item.vue(node:462508) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be
of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at getSassOptions (C:\project\webstorm\aliemail\node_modules\sass-loader\dist\utils.js:166:37)
    at Object.loader (C:\project\webstorm\aliemail\node_modules\sass-loader\dist\index.js:43:55)
    at LOADER_EXECUTION (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at Object.context.callback (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.module.exports (C:\project\webstorm\aliemail\node_modules\vue-loader\lib\selector.js:21:8)
    at LOADER_EXECUTION (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:205:4
    at C:\project\webstorm\aliemail\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70:14
(node:462508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whi
ch was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_re
jections_mode). (rejection id: 3)
(node:462508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exi
t code.
(node:462508) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at getSassOptions (C:\project\webstorm\aliemail\node_modules\sass-loader\dist\utils.js:166:37)
    at Object.loader (C:\project\webstorm\aliemail\node_modules\sass-loader\dist\index.js:43:55)
    at LOADER_EXECUTION (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at Object.context.callback (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.module.exports (C:\project\webstorm\aliemail\node_modules\vue-loader\lib\selector.js:21:8)
    at LOADER_EXECUTION (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at C:\project\webstorm\aliemail\node_modules\loader-runner\lib\LoaderRunner.js:205:4
    at C:\project\webstorm\aliemail\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70:14
(node:462508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whi
ch was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_re
jections_mode). (rejection id: 4)

**Comment by mehaotian** [comment]
uni-ui 目前还没对 vue 项目进行支持

**Comment by mehaotian** [comment]
issue 暂时关闭，如仍有问题请 reopen issue。
