### ISSUE TITLE
[vue warn] H5中 swipe-action 和 swipe-action-item 报错 遍历一次 报错一次 但是不影响跑代码 就是报错

### ISSUE THREAD

**Issue by w1o9960720** [dcloudio/uni-ui#494]
chunk-vendors.js:2773 [Vue warn]: Error in callback for immediate watcher "is_show": "TypeError: Cannot read properties of undefined (reading 'querySelector')"

found in

---> <UniSwipeActionItem> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action-item/uni-swipe-action-item.vue
       <UniSwipeAction> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue

**Comment by mehaotian** [comment]
什么环境下？

**Comment by w1o9960720** [comment]
我发现是 hbuildex版本好像更新为4.7&nbsp; &nbsp;后面我把版本降低了&nbsp; 就不报错&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;是h5 报错&nbsp; &nbsp; &nbsp;小程序和app都不报错&nbsp; &nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月7日(星期六) 上午9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-ui] [vue warn] H5中 swipe-action 和 swipe-action-item 报错 遍历一次 报错一次 但是不影响跑代码 就是报错 (Issue #494)





 
什么环境下？

**Comment by lanbing4191** [comment]
HbuilderX 3.4.7版本也有相同警告

**Comment by w1o9960720** [comment]
就是这版本  而且我现在3.4.6 也报错  我记得3.3.9没有报错    现在报两错


chunk-vendors.js:2261 [Vue warn]: Error in callback for immediate watcher "is_show": "TypeError: Cannot read properties of undefined (reading 'querySelector')"

found in

---> <UniSwipeActionItem> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action-item/uni-swipe-action-item.vue
       <UniSwipeAction> at node_modules/@dcloudio/uni-ui/lib/uni-swipe-action/uni-swipe-action.vue



[system] TypeError: Cannot read properties of undefined (reading 'querySelector')
    at Object.getDom (pages-dataApproval-index~pages-dataApproval-site~pages-dataApproval-thirdRecord~pages-monitorAudit-i~f191a012.js:1665:37)
    at Object.showWatch (pages-dataApproval-index~pages-dataApproval-site~pages-dataApproval-thirdRecord~pages-monitorAudit-i~f191a012.js:1555:10)
    at VueComponent.showWatch (pages-dataApproval-index~pages-dataApproval-site~pages-dataApproval-thirdRecord~pages-monitorAudit-i~f191a012.js:978:23)
    at VueComponent.vnode.$wxsWatches.<computed>.oldWxsWatches.<computed>.vnode.context.$watch.immediate (chunk-vendors.js:8423:21)
    at VueComponent.Vue.$watch (chunk-vendors.js:6638:12)
    at chunk-vendors.js:8422:68
    at Array.forEach (<anonymous>)
    at Array.updateWxsProps (chunk-vendors.js:8415:25)
    at invokeCreateHooks (chunk-vendors.js:7756:22)
    at initComponent (chunk-vendors.js:7689:7)

**Comment by mehaotian** [comment]
报错问题 ，升级 HBuilderX 3.4.12+
