### ISSUE TITLE
vue3+uni-starter下，uni-table无法渲染第二行

### ISSUE THREAD

**Issue by mikeshi80** [dcloudio/uni-ui#523]
当使用schema2code生成了相应页面，但是我试图在该页面下，生成一个`uni-table`时，当写到第二个tr时，会出现以下错误

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__composer')
    at Proxy.mounted (vue-i18n.esm-bundler.js:1763:52)
    at callWithErrorHandling (vue.runtime.esm.js:1309:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1318:21)
    at hook.__weh.hook.__weh (vue.runtime.esm.js:3988:29)
    at flushPostFlushCbs (vue.runtime.esm.js:1511:47)
    at flushJobs (vue.runtime.esm.js:1556:9)
```

经debug是因为这里的`this.$i18n`为undefined，所以造成语句失败。但是第一行tr却是正常的。

我在`uni-starter.config.js`中，将i18n设为了false。

但是奇怪的是，同样是vue3，但是我生成的`uni-admin`项目，`uni-table`是正常显示的。

HBuildX的版本为3.4.7.20220422，`uni-table`的版本为 1.20（后升级到1.21也一样的表现）

系统为Win10

**Comment by linju-json** [comment]
请加任意uniCloud官方交流群@DCloud_JSON给你看一下

**Comment by codexu** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
