### ISSUE TITLE
使用 yarn 安装报错

### ISSUE THREAD

**Issue by Jocs** [dcloudio/uni-ui#82]
错误信息如下

```sh
 error  in ./node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue?vue&type=style&index=0&id=154342f4&lang=scss&scoped=true&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

		animation: loading-ios-H5 1s 0s step-end infinite;
^
      File to import not found or unreadable: @/uni.scss.
      in /Users/ransixi/Documents/echo/cactus/node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue (line 153, column 1)
    at /Users/ransixi/Documents/echo/cactus/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/ransixi/Documents/echo/cactus/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/ransixi/Documents/echo/cactus/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/ransixi/Documents/echo/cactus/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.callback (/Users/ransixi/Documents/echo/cactus/node_modules/sass-loader/dist/index.js:89:7)
    at Object.done [as callback] (/Users/ransixi/Documents/echo/cactus/node_modules/neo-async/async.js:8067:18)
    at options.error (/Users/ransixi/Documents/echo/cactus/node_modules/node-sass/lib/index.js:294:32)

 @ ./node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue?vue&type=style&index=0&id=154342f4&lang=scss&scoped=true& 1:0-747 1:763-766 1:768-1512 1:768-1512
 @ ./node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/components/load-more.vue?vue&type=script&lang=js&
 @ ./src/components/load-more.vue?vue&type=script&lang=js&
 @ ./src/components/load-more.vue
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages-consignment/transaction-records/index.vue?vue&type=script&lang=js&
 @ ./src/pages-consignment/transaction-records/index.vue?vue&type=script&lang=js&
 @ ./src/pages-consignment/transaction-records/index.vue
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages-consignment/index.vue?vue&type=script&lang=js&
 @ ./src/pages-consignment/index.vue?vue&type=script&lang=js&
 @ ./src/pages-consignment/index.vue
 @ ./src/main.js?{"page":"pages-consignment%2Findex"}

 ERROR  Build failed with errors.
```

node: v13.1.0
yarn: 1.19.1
uni-ui: 1.0.7

**Comment by javascriptchen** [comment]
你要装sass-loader跟node-sass
